environment:
    TARGET: 1.10.0-x86_64-pc-windows-gnu
    MSYS2_BITS: 64
install:
    - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe"
    - rust-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
    - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
    - if defined MSYS2_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS2_BITS%\bin
    - rustc -V
    - cargo -V
    - ps: Start-FileDownload "http://sqlite.org/2016/sqlite-dll-win64-x64-3130000.zip"
    - cmd: 7z e sqlite-dll-win64-x64-3130000.zip -y > nul
    - SET SQLITE3_LIB_DIR=%APPVEYOR_BUILD_FOLDER%
    - echo %SQLITE3_LIB_DIR%

build_script:
    - cargo build --release
    - cargo build

artifacts:
    - path: target\release\mymdb.exe
      name: release

    - path: target\debug\mymdb.exe
      name: debug

cache:
    - C:\Users\appveyor\.cargo
