[package]
name = "mymdb"
version = "0.3.1"
authors = ["cheezgi <zackh@firelmail.cc>"]

[dependencies] #these are all *really* out of date probably
rusqlite = "0.6.0"
time = "0.1.35"
rand = "0.3.14"
regex = "0.1.68"
